"""
Synthetic Dataset Generator for Customer Suspension Notification Agent.
Proof-of-concept generator for SLT internship project.

DISCLAIMER:
All data generated by this script is 100% fictional and synthetic.
No real customer names, phone numbers, or emails are used.
"""

import os
import csv
import random
import argparse
from typing import List, Dict

# Specific test cases required to be placed at predictable positions
DETERMINISTIC_TEST_CASES = [
    {
        "id": 1,
        "name": "Customer 001",
        "land_number": "0116789001",
        "whatsapp_number": "+94770000001",
        "email": "customer001@example.com",
        "status": "Active",
        "remark": "Account in good standing",  # Case A: Active customer
    },
    {
        "id": 2,
        "name": "Customer 002",
        "land_number": "0116789002",
        "whatsapp_number": "+94770000002",
        "email": "customer002@example.com",
        "status": "Suspended",
        "remark": "Bill overdue",  # Case B: Bill overdue
    },
    {
        "id": 3,
        "name": "Customer 003",
        "land_number": "0116789003",
        "whatsapp_number": "+94770000003",
        "email": "customer003@example.com",
        "status": "Suspended",
        "remark": "Payment not received",  # Case C: Payment not received
    },
    {
        "id": 4,
        "name": "Customer 004",
        "land_number": "0116789004",
        "whatsapp_number": "+94770000004",
        "email": "customer004@example.com",
        "status": "Suspended",
        "remark": "Customer requested temporary suspension",  # Case D: Customer requested
    },
    {
        "id": 5,
        "name": "Customer 005",
        "land_number": "0116789005",
        "whatsapp_number": "+94770000005",
        "email": "customer005@example.com",
        "status": "Suspended",
        "remark": "Technical issue",  # Case E: Technical issue
    },
    {
        "id": 6,
        "name": "Customer 006",
        "land_number": "0116789006",
        "whatsapp_number": "+94770000006",
        "email": "customer006@example.com",
        "status": "Suspended",
        "remark": "Account issue",  # Case F: Account issue
    },
    {
        "id": 7,
        "name": "Customer 007",
        "land_number": "0116789007",
        "whatsapp_number": "+94770000007",
        "email": "",  # Case G: Missing email
        "status": "Suspended",
        "remark": "Bill overdue",
    },
    {
        "id": 8,
        "name": "Customer 008",
        "land_number": "0116789008",
        "whatsapp_number": "+94770000008",
        "email": "",  # Case G variant: Missing email with customer request
        "status": "Suspended",
        "remark": "Customer requested service suspension",
    },
]

SUSPENSION_REMARKS = [
    # Bill overdue variations
    "Bill overdue",
    "Unpaid bill",
    "Outstanding payment",
    # Payment not received variations
    "Payment not received",
    "Non-payment of monthly charges",
    # Customer requested variations
    "Customer requested temporary suspension",
    "Customer requested service suspension",
    "Temporary suspension requested by customer",
    # Technical issue variations
    "Technical issue",
    "Service issue",
    "Line maintenance",
    # Account / KYC issue variations
    "Account issue",
    "Verification required",
    "Identity verification pending",
]

ACTIVE_REMARKS = [
    "Account active",
    "Normal service",
    "In good standing",
    "Active subscriber",
    "Standard billing",
    "",
]


def generate_customers(count: int = 100, seed: int = 42) -> List[Dict[str, str]]:
    """Generate synthetic customer dataset with realistic ~70/30 distribution."""
    random.seed(seed)
    records: List[Dict[str, str]] = []

    # Insert deterministic test cases first
    for case in DETERMINISTIC_TEST_CASES:
        records.append({
            "land_number": case["land_number"],
            "customer_name": case["name"],
            "whatsapp_number": case["whatsapp_number"],
            "email": case["email"],
            "status": case["status"],
            "remark": case["remark"],
        })

    # Generate remaining records up to `count`
    current_count = len(records)
    for i in range(current_count + 1, count + 1):
        padded_id = f"{i:03d}" if i < 1000 else f"{i:04d}"
        land_number = f"011{6789000 + i:07d}"
        whatsapp_number = f"+9477{1000000 + i:07d}"
        customer_name = f"Customer {padded_id}"
        
        # Decide status: roughly 70% Active, 30% Suspended
        is_suspended = (random.random() < 0.30)
        
        if is_suspended:
            status = "Suspended"
            remark = random.choice(SUSPENSION_REMARKS)
            # About 5% of suspended customers have missing email (Case G)
            if random.random() < 0.05:
                email = ""
            else:
                email = f"customer{padded_id}@example.com"
        else:
            status = "Active"
            remark = random.choice(ACTIVE_REMARKS)
            email = f"customer{padded_id}@example.com"

        records.append({
            "land_number": land_number,
            "customer_name": customer_name,
            "whatsapp_number": whatsapp_number,
            "email": email,
            "status": status,
            "remark": remark,
        })

    return records


def save_to_csv(records: List[Dict[str, str]], filepath: str) -> None:
    """Save customer records to a CSV file."""
    os.makedirs(os.path.dirname(os.path.abspath(filepath)), exist_ok=True)
    fieldnames = ["land_number", "customer_name", "whatsapp_number", "email", "status", "remark"]
    
    with open(filepath, mode="w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(records)


def validate_records(records: List[Dict[str, str]]) -> Dict[str, any]:
    """Validate generated records and print statistical summary."""
    total = len(records)
    active = sum(1 for r in records if r["status"] == "Active")
    suspended = sum(1 for r in records if r["status"] == "Suspended")
    missing_email = sum(1 for r in records if not r["email"].strip())
    
    return {
        "total": total,
        "active": active,
        "active_pct": round((active / total) * 100, 1),
        "suspended": suspended,
        "suspended_pct": round((suspended / total) * 100, 1),
        "missing_email": missing_email,
    }


def main():
    parser = argparse.ArgumentParser(description="Generate synthetic customer dataset for SLT internship POC.")
    parser.add_argument("--count", type=int, default=100, help="Number of customer records to generate (default: 100)")
    parser.add_argument("--seed", type=int, default=42, help="Random seed for reproducibility (default: 42)")
    parser.add_argument("--output", type=str, default="data/customers.csv", help="Output file path (default: data/customers.csv)")
    args = parser.parse_args()

    records = generate_customers(count=args.count, seed=args.seed)
    save_to_csv(records, args.output)
    stats = validate_records(records)

    print("=" * 60)
    print("SYNTHETIC CUSTOMER DATASET GENERATED SUCCESSFULLY")
    print("=" * 60)
    print(f"Output File:      {args.output}")
    print(f"Total Records:    {stats['total']}")
    print(f"Active Customers: {stats['active']} ({stats['active_pct']}%)")
    print(f"Suspended Cust.:  {stats['suspended']} ({stats['suspended_pct']}%)")
    print(f"Missing Emails:   {stats['missing_email']}")
    print("=" * 60)
    print("All test cases (A, B, C, D, E, F, G) included in first 8 records.")


if __name__ == "__main__":
    main()
